# BACKGROUND
background {
    monitor =
    path = ~/.config/hyprlock/hyprlock.jpg
    blur_passes = 0
    blur_size = 0
    contrast = 0.96
    brightness = 0.90
    vibrancy = 0.06
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# TIME — крупнее, ближе к macOS lockscreen
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%-I:%M%p")"
    color = rgba(250, 189, 47, 0.78)
    font_size = 154
    font_family = Adwaita Sans
    position = 0, -92
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A, %d %B')"
    color = rgba(245, 245, 245, 0.78)
    font_size = 40
    font_family = Adwaita Sans
    position = 10, 275
    halign = center
    valign = center
}

# USER ICON
image {
    monitor =
    path = ~/.config/hyprlock/user-icon.jpg
    size = 400
    rounding = 200
    border_size = 0
    position = 0, 20
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = Hello, $USER
    color = rgba(255, 255, 255, 0.74)
    font_size = 38
    font_family = Adwaita Sans
    position = -10, -265
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 58
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.20
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.10)
    inner_color = rgba(40, 40, 40, 0.36)
    font_color = rgba(255, 255, 255, 0.88)
    fade_on_empty = false
    font_family = Adwaita Sans
    placeholder_text = Password...
    hide_input = false
    position = 0, -360
    halign = center
    valign = center
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hyprlock/Scripts/songdetail.sh)"
    color = rgba(235, 219, 178, 0.84)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 130
    halign = center
    valign = bottom
}
